### ISSUE TITLE
missing ui assets

### ISSUE THREAD

**Issue by scottleedavis** [Netflix/sleepy-puppy-docker#1]
The branch sleepy-puppy is pulled from, is missing assets in the UI that make it near unusable.

fails w/404's on:
- static/admin/vendor/jquery-2.1.1.min.js
- static/admin/bootstrap/bootstrap3/css/bootstrap.min.css
- static/admin/bootstrap/bootstrap3/css/bootstrap-theme.min.css
- static/admin/admin/css/bootstrap3/admin.css
- static/admin/bootstrap/bootstrap3/js/bootstrap.min.js
- static/admin/vendor/moment-2.8.4.min.js
- static/admin/vendor/select2/select2.min.js

**Comment by sbehrens** [comment]
Tracking on main repo.  https://github.com/Netflix/sleepy-puppy/issues/1

**Comment by scriptsrc** [comment]
I haven't committed any changes yet, but it appears to be fixed if you remove the following from `nginx/sites-available/sleepy_puppy`

```
location /static {
    alias /usr/local/src/sleepy-puppy/sleepypuppy/static;
    autoindex on;
}
```

I'll test this a bit more and update the repo when I'm ready.

**Comment by sbehrens** [comment]
Resolved in latest commit to master.
